# Generated by Django 6.0.1 on 2026-01-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0003_auto_20260126_1914"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
